import { RED_FLAG_QUESTIONS_LIST } from '@/config/redFlagQuestions'

export const darkTokens = {
  bg: '#0e1016',
  bg2: '#141820',
  surface: '#181e2a',
  surface2: '#1e2535',
  surface3: '#242d40',
  border: '#2c3650',
  borderSoft: '#232d42',
  red: '#C00000',
  redBright: '#e03030',
  redMuted: 'rgba(192,0,0,0.12)',
  redBorder: 'rgba(192,0,0,0.35)',
  blue: '#1C2852',
  blueBright: '#4a6fd4',
  blueMuted: 'rgba(74,111,212,0.12)',
  blueBorder: 'rgba(74,111,212,0.4)',
  gold: '#C4B696',
  goldBright: '#d9cdb0',
  goldMuted: 'rgba(196,182,150,0.1)',
  goldBorder: 'rgba(196,182,150,0.3)',
  green: '#1a9e78',
  greenBright: '#22c997',
  greenMuted: 'rgba(26,158,120,0.12)',
  greenBorder: 'rgba(34,201,151,0.35)',
  text: '#dde3f0',
  textDim: '#6e7d99',
  textMuted: '#3d4a62',
}

export const lightTokens = {
  bg: '#f0f2f7',
  bg2: '#e8eaf2',
  surface: '#ffffff',
  surface2: '#f5f6fa',
  surface3: '#eceef5',
  border: '#d4d8e8',
  borderSoft: '#dfe2ee',
  red: '#C00000',
  redBright: '#C00000',
  redMuted: 'rgba(192,0,0,0.07)',
  redBorder: 'rgba(192,0,0,0.3)',
  blue: '#1C2852',
  blueBright: '#1C2852',
  blueMuted: 'rgba(28,40,82,0.07)',
  blueBorder: 'rgba(28,40,82,0.3)',
  gold: '#8a7650',
  goldBright: '#7a6640',
  goldMuted: 'rgba(138,118,80,0.08)',
  goldBorder: 'rgba(138,118,80,0.3)',
  green: '#1a7a5e',
  greenBright: '#1a7a5e',
  greenMuted: 'rgba(26,122,94,0.08)',
  greenBorder: 'rgba(26,122,94,0.3)',
  text: '#1C2852',
  textDim: '#5a6882',
  textMuted: '#a0aac0',
}

export const FLAGS: FlagCard[] = RED_FLAG_QUESTIONS_LIST
export const SEGMENTS = [
  {
    icon: '💰',
    iconBg: 'rgba(192,0,0,0.12)',
    title: 'Capital & Cash',
    desc: 'Is the business creating or destroying wealth?',
    flagIds: [1, 2, 3],
  },
  {
    icon: '🎭',
    iconBg: 'rgba(196,182,150,0.1)',
    title: 'Fake Profits & Margins',
    desc: 'Are reported profits real, or accounting smoke and mirrors?',
    flagIds: [4, 5],
  },
  {
    icon: '⚖️',
    iconBg: 'rgba(74,111,212,0.12)',
    title: 'Hidden Balance Sheet Traps',
    desc: "What's lurking that could detonate quietly?",
    flagIds: [6, 7],
  },
  {
    icon: '🕵️',
    iconBg: 'rgba(192,0,0,0.12)',
    title: 'Shady Promoters & Governance',
    desc: 'Can you trust the people running this company with your money?',
    flagIds: [8, 9, 10],
  },
]

export const COMBOS: Combo[] = [
  {
    id: 1,
    tier: 'critical',
    flags: [2, 4],
    name: 'The Fake Growth Trap',
    desc: 'Negative FCF + Poor Cash Conversion. Revenue grows on paper, but cash never arrives and EBITDA-to-CFO conversion stays below 50%. Both metrics independently confirm the same truth: this business cannot turn profits into real money.',
    flagsLabel: 'Triggers: Flag 02 + Flag 04',
    alert: '⚠ ACTIVE — LIKELY FAKE REVENUE',
  },
  {
    id: 2,
    tier: 'critical',
    flags: [1, 3, 6],
    name: 'The Sunk Cost Spiral',
    desc: 'Low ROCE + High Debt + Stuck CWIP. Borrowing heavily to build assets that are perpetually delayed and earn nothing. Capital is disappearing into the ground with no return in sight.',
    flagsLabel: 'Triggers: Flag 01 + Flag 03 + Flag 06',
    alert: '⚠ ACTIVE — CAPITAL DESTRUCTION IN PROGRESS',
  },
  {
    id: 3,
    tier: 'critical',
    flags: [8, 10],
    name: 'The Fraud Precursor',
    desc: 'Messy RPTs + High Promoter Pledging. Promoter is siphoning via related parties while personally leveraged against the same stock. Total capital wipeout typically follows. Do not wait for confirmation.',
    flagsLabel: 'Triggers: Flag 08 + Flag 10',
    alert: '⚠ ACTIVE — EXIT IMMEDIATELY',
  },
  {
    id: 4,
    tier: 'critical',
    flags: [2, 9],
    name: 'The Structural Cash Hemorrhage',
    desc: 'Negative FCF + Unhealthy Fund Flow. Operations bleed money AND the only lifeline is constant debt or equity dilution. No viable path to self-sufficiency exists. The business model is fundamentally broken.',
    flagsLabel: 'Triggers: Flag 02 + Flag 09',
    alert: '⚠ ACTIVE — BUSINESS MODEL IS BROKEN',
  },
  {
    id: 5,
    tier: 'critical',
    flags: [1, 2, 4],
    name: 'The Triple Cash Failure',
    desc: 'Low ROCE + Negative FCF + Poor Cash Conversion. All three cash-quality metrics failing simultaneously. The company is neither efficient, nor converting, nor generating real money. Deeply structurally broken.',
    flagsLabel: 'Triggers: Flag 01 + Flag 02 + Flag 04',
    alert: '⚠ ACTIVE — FUNDAMENTAL CASH DESTRUCTION',
  },
  {
    id: 6,
    tier: 'high',
    flags: [1, 2],
    name: 'The Wealth Destroyer',
    desc: 'Low ROCE + Negative FCF. Earning below cost of capital and generating no real cash. The business actively destroys shareholder value with every passing year it continues in this state.',
    flagsLabel: 'Triggers: Flag 01 + Flag 02',
    turnaround:
      '⚡ Turnaround Exception: Only acceptable if ROCE is visibly improving quarter-on-quarter and the FCF trajectory is clearly reversing with a credible, time-bound plan. Evidence required — not just management commentary.',
    alert: '⚠ ACTIVE — HIGH RISK',
  },
  {
    id: 7,
    tier: 'high',
    flags: [1, 3],
    name: 'The Debt Trap',
    desc: 'Low ROCE + High & Rising Debt. Earning below cost of capital while piling on more debt. Interest burden compounds faster than earnings can grow to meet it. A slow but inevitable death spiral.',
    flagsLabel: 'Triggers: Flag 01 + Flag 03',
    turnaround:
      '⚡ Turnaround Exception: Acceptable only if debt is financing a high-return expansion with a clear payoff date, AND ROCE is actively improving. Management commentary alone is not sufficient.',
    alert: '⚠ ACTIVE — HIGH RISK',
  },
  {
    id: 8,
    tier: 'high',
    flags: [2, 3],
    name: 'Survival Mode',
    desc: 'Negative FCF + High Debt. Cannot fund itself from operations; surviving purely on borrowed money. Any credit tightening, rate rise, or bank nervousness can trigger an immediate liquidity crisis.',
    flagsLabel: 'Triggers: Flag 02 + Flag 03',
    turnaround:
      '⚡ Turnaround Exception: A company in a heavy investment phase can temporarily show negative FCF and rising debt before new capacity starts generating cash. Only acceptable if there is a clear, time-bound capex cycle nearing completion with improving operational metrics.',
    alert: '⚠ ACTIVE — LIQUIDITY RISK',
  },
  {
    id: 9,
    tier: 'high',
    flags: [3, 6],
    name: 'Debt-Funded Nowhere',
    desc: 'High Debt + Stuck CWIP. Borrowing heavily to build a project that never completes. Debt accumulates and interest compounds; the asset produces nothing. Eventually the interest cost overwhelms the balance sheet.',
    flagsLabel: 'Triggers: Flag 03 + Flag 06',
    turnaround:
      '⚡ Turnaround Exception: If CWIP delay is due to verified external factors (regulatory approvals, land disputes) and the project is genuinely near completion with a specific go-live date — not just management promises — this can be a monitored position.',
    alert: '⚠ ACTIVE — HIGH RISK',
  },
  {
    id: 10,
    tier: 'high',
    flags: [3, 10],
    name: 'The Margin Call Bomb',
    desc: 'High Debt + High Promoter Pledging. The company is leveraged AND the promoter is personally leveraged against the same stock. A market correction can trigger simultaneous company-level and promoter-level default.',
    flagsLabel: 'Triggers: Flag 03 + Flag 10',
    alert: '⚠ ACTIVE — DOUBLE LEVERAGE RISK',
  },
  {
    id: 11,
    tier: 'high',
    flags: [8, 9],
    name: 'The Promoter Drain',
    desc: 'Messy RPTs + Unhealthy Fund Flow. Cash entering the business immediately leaks out to promoter-linked entities. The Tijori fund flow map will show money exiting through operating or financing channels to related parties.',
    flagsLabel: 'Triggers: Flag 08 + Flag 09',
    alert: '⚠ ACTIVE — PROMOTER SIPHONING RISK',
  },
  {
    id: 12,
    tier: 'high',
    flags: [3, 5],
    name: 'The Cyclical Debt Disaster',
    desc: 'Volatile Margins (commodity business) + High Debt. No pricing power combined with high leverage is catastrophic in a downturn. Margins compress exactly when debt repayment stress is at its highest.',
    flagsLabel: 'Triggers: Flag 03 + Flag 05',
    turnaround:
      '⚡ Turnaround Exception: A commodity business at the bottom of a proven industry cycle with manageable debt and a history of surviving previous downturns may recover when the cycle turns. Requires clear evidence you are near cycle bottom — not just hope.',
    alert: '⚠ ACTIVE — CYCLICAL COLLAPSE RISK',
  },
  {
    id: 13,
    tier: 'high',
    flags: [3, 7],
    name: 'The Debt-Funded Acquisition Gamble',
    desc: 'Goodwill ≈ Net Worth + High Debt. Overpaid for an acquisition and funded it with debt. If the acquired business underperforms, a goodwill write-off wipes equity while the debt remains. Double pain, no escape.',
    flagsLabel: 'Triggers: Flag 03 + Flag 07',
    alert: '⚠ ACTIVE — ACQUISITION BLOW-UP RISK',
  },
  {
    id: 14,
    tier: 'high',
    flags: [2, 6],
    name: 'The Capital Graveyard',
    desc: 'Negative FCF + Stuck CWIP. Money is sinking into an incomplete project that generates nothing, while the existing business also fails to generate free cash. Capital is trapped on both fronts with no near-term exit.',
    flagsLabel: 'Triggers: Flag 02 + Flag 06',
    turnaround:
      '⚡ Turnaround Exception: If the stuck CWIP is verifiably close to completion (specific commissioning date, construction nearly done) and existing operations show improving FCF trajectory, the thesis can hold. Both conditions must be true — not just one.',
    alert: '⚠ ACTIVE — CAPITAL FULLY TRAPPED',
  },
  {
    id: 15,
    tier: 'high',
    flags: [4, 7],
    name: 'The Hollow Acquisition',
    desc: 'Poor Cash Conversion + Goodwill ≈ Net Worth. The company overpaid for an acquisition AND cannot convert its own profits into cash. Both the legacy business and the acquired business are underperforming — equity is doubly at risk.',
    flagsLabel: 'Triggers: Flag 04 + Flag 07',
    alert: '⚠ ACTIVE — EARNINGS QUALITY EXTREMELY LOW',
  },
  {
    id: 16,
    tier: 'high',
    flags: [1, 5],
    name: 'The Commodity Trap',
    desc: 'Low ROCE + Volatile Margins. No pricing power and no capital efficiency. Management claims specialty status; the numbers prove otherwise. You are paying a premium multiple for a commodity producer.',
    flagsLabel: 'Triggers: Flag 01 + Flag 05',
    turnaround:
      '⚡ Turnaround Exception: A commodity business at the bottom of its cycle can show temporarily low ROCE and volatile margins before recovering. Acceptable only if there is a clear industry cycle thesis, the balance sheet is clean enough to survive the downturn, and management is not dressing it up as "specialty."',
    alert: '⚠ ACTIVE — OVERVALUED COMMODITY BUSINESS',
  },
  {
    id: 17,
    tier: 'high',
    flags: [1],
    name: 'The Dead Capital Business',
    desc: 'Low ROCE — standalone. A business with persistently low ROCE and no credible path to improving it is a value trap regardless of how cheap the valuation looks. Capital deployed here earns less than it cost to raise. Time destroys value in these companies even if nothing else "goes wrong."',
    flagsLabel: 'Triggers: Flag 01 (standalone)',
    turnaround:
      '⚡ Turnaround Exception: The only acceptable scenario is an active, time-bound turnaround where ROCE is already showing measurable quarterly improvement — not a promise of future improvement. If management has been saying "ROCE will improve" for 3+ years with no data to back it, there is no turnaround. Walk away.',
    alert: '⚠ ACTIVE — AVOID UNLESS TURNAROUND IS PROVEN',
  },
  {
    id: 18,
    tier: 'high',
    flags: [5, 7],
    name: 'The Overvalued Acquirer',
    desc: 'Volatile Margins (commodity) + Goodwill ≈ Net Worth. A business with no pricing power that also overpaid for an acquisition. When the cycle turns down, both margins compress AND goodwill faces write-off risk simultaneously.',
    flagsLabel: 'Triggers: Flag 05 + Flag 07',
    alert: '⚠ ACTIVE — HIGH RISK',
  },
  {
    id: 19,
    tier: 'high',
    flags: [1, 6],
    name: 'The Expanding Underperformer',
    desc: 'Low ROCE + Stuck CWIP. The business earns below cost of capital on existing assets and is simultaneously sinking more capital into a delayed expansion. Adding capacity to an already poor-return business compounds the value destruction.',
    flagsLabel: 'Triggers: Flag 01 + Flag 06',
    turnaround:
      '⚡ Turnaround Exception: If the new capacity (CWIP) is structurally different from existing operations — higher-margin product, new geography, contracted offtake — and ROCE is expected to improve materially once commissioned. Requires specific evidence, not hope.',
    alert: '⚠ ACTIVE — HIGH RISK',
  },
  {
    id: 20,
    tier: 'high',
    flags: [4, 9],
    name: 'The Governance Cash Leak',
    desc: 'Poor Cash Conversion + Messy RPTs. Cash conversion is poor AND related party transactions are messy. This combination raises a specific question: is the cash conversion poor because of genuine operational issues, or because profits are being quietly redirected to promoter-linked entities before they reach the books?',
    flagsLabel: 'Triggers: Flag 04 + Flag 08',
    alert: '⚠ ACTIVE — GOVERNANCE CASH DIVERSION RISK',
  },
]
