export const AppRoutes = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  contact: "/contact-us",
  careerPage: "/careers",
  singleCareerPage: "/careers/:slug",
  refundPolicy: "/refund-policy",
  privacyPolicy: "/privacy-policy",
  termAndCondition: "/terms-and-conditions",
  compliance: "/compliance",
  bastionCore: "/bastion-core",
  editProfile: "/edit-profile",
  subscription: "/subscription",
  transactionHistory: "/transaction-history",
  spotlights: "/spotlights",
  podcasts: "/podcasts",
  about: "/about",
  test: "/test",
  newsletter: "/newsletters-archive",
  scratch_pad_newsletter: "/user/app/scratch-pad",
  webinar: "/webinars",
  smartFrameworks: "/smart-frameworks",
  research: "/research",
  paymentSuccess: "/payment/success",
  comingSoon: "/coming-soon",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminManageMembers: "/admin/ar/members",
  adminManagePlans: "/admin/ar/plans",
  adminManageSubscriptions: "/admin/ar/subscriptions",
  adminPaymentHistory: "/admin/ar/payments",
  adminCouponManagement: "/admin/ar/coupons",
  adminJobOpenings: "/admin/jobs/openings",
  adminAddNewJob: "/admin/jobs/add",
  adminApplications: "/admin/jobs/applications",
  adminLeads: "/admin/leads",
  adminAllUsers: "/admin/users/all",
  adminProfile: "/admin/users/profile",
  adminSettings: "/admin/settings",
  editor: "/admin/editor",
  ipoUserDashboard: "/ipo-dashboard",
  allIpos: "/all-ipos",
  // Content management routes
  adminNewsletterManagement: "/admin/content/newsletters",
  adminWebinarManagement: "/admin/content/webinars",
  adminPodcastManagement: "/admin/content/podcasts",
  adminNewsletterCreate: "/admin/content/newsletters/create",
  adminNewsletterEdit: "/admin/content/newsletters/:id/edit",
  adminWebinarCreate: "/admin/content/webinars/create",
  adminWebinarEdit: "/admin/content/webinars/:id/edit",
  adminPodcastCreate: "/admin/content/podcasts/create",
  adminPodcastEdit: "/admin/content/podcasts/:id/edit",
  adminResearchManagement: "/admin/content/research",
  adminScratchPadCreate: "/admin/content/scratch-pad/create",
  adminScratchPadEdit: "/admin/content/scratch-pad/:id/edit",
  adminScratchPadManagement: "/admin/content/scratch-pad",
  adminResearchCreate: "/admin/content/research/create",
  adminResearchEdit: "/admin/content/research/:id/edit",
  adminTestimonialManagement: "/admin/content/testimonials",
  adminTestimonialCreate: "/admin/content/testimonials/create",
  adminTestimonialEdit: "/admin/content/testimonials/:id/edit",
  adminRecommendationManagement: "/admin/content/recommendations",
  userRoute: "/user",
  premiumWebinars: "/user/app/premium-webinars",
  singlePremiumWebinar: "/user/app/premium-webinars/:id",
  newsletterView: "/newsletters/:id",
  webinarView: "/webinars/:id",

  podcastView: "/podcasts/:id",
  researchView: "/research/:id",
  scratchPadView: "/scratch-pad/:id",
  ipoLanding: "/ipo-landing",
} as const;

export const AuthRoutes = [
  AppRoutes.login,
  AppRoutes.forgotPassword,
  AppRoutes.resetPassword,
];
