export const AppRoutes = {
  home: () => "/",
  login: () => "/login",
  register: () => "/register",
  forgotPassword: () => "/forgot-password",
  resetPassword: () => "/reset-password",
  dashboard: () => "/dashboard",
  contact: () => "/contact",
  careerPage: () => "/careers",
  singleCareerPage: () => "/careers/:slug",
  refundPolicy: () => "/refund-policy",
  privacyPolicy: () => "/privacy-policy",
  termAndCondition: () => "/terms-and-conditions",
  compliance: () => "/compliance",
  bastionCore: () => "/bastion-core",
  editProfile: () => "/edit-profile",
  subscription: () => "/subscription",
  transactionHistory: () => "/transaction-history",
  spotlights: () => "/spotlights",
  podcasts: () => "/podcasts",
  about: () => "/about",
  test: () => "/test",
  newsletter: () => "/newsletters-archive",
  webinar: () => "/webinars",
  smartFrameworks: () => "/smart-frameworks",
  paymentSuccess: () => "/payment/success",
  admin: () => "/admin",
  adminLogin: () => "/admin/login",
  adminDashboard: () => "/admin/dashboard",
  adminManageMembers: () => "/admin/ar/members",
  adminManagePlans: () => "/admin/ar/plans",
  adminManageSubscriptions: () => "/admin/ar/subscriptions",
  adminPaymentHistory: () => "/admin/ar/payments",
  adminCouponManagement: () => "/admin/ar/coupons",
  adminJobOpenings: () => "/admin/jobs/openings",
  adminAddNewJob: () => "/admin/jobs/add",
  adminApplications: () => "/admin/jobs/applications",
  adminAllUsers: () => "/admin/users/all",
  adminAddUser: () => "/admin/users/add",
  adminProfile: () => "/admin/users/profile",
  adminSettings: () => "/admin/settings",
  editor: () => "/admin/editor",
};

export const AuthRoutes = [
  AppRoutes.login(),
  AppRoutes.register(),
  AppRoutes.forgotPassword(),
  AppRoutes.resetPassword(),
];
