export const AppRoutes = {
  home: () => "/",
  login: () => "/login",
  register: () => "/register",
  forgotPassword: () => "/forgot-password",
  resetPassword: () => "/reset-password",
  dashboard: () => "/dashboard",
  contact: () => "/contact-us",
  careerPage: () => "/careers",
  singleCareerPage: () => "/careers/:slug",
  refundPolicy: () => "/refund-policy",
  privacyPolicy: () => "/privacy-policy",
  termAndCondition: () => "/terms-and-conditions",
  compliance: () => "/compliance",
  bastionCore: () => "/bastion-core",
  editProfile: () => "/edit-profile",
  subscription: () => "/subscription",
  transactionHistory: () => "/transaction-history",
  spotlights: () => "/spotlights",
  podcasts: () => "/podcasts",
  about: () => "/about",
  test: () => "/test",
  newsletter: () => "/newsletters-archive",
  webinar: () => "/webinars",
  smartFrameworks: () => "/smart-frameworks",
  research: () => "/research",
  paymentSuccess: () => "/payment/success",
  admin: () => "/admin",
  adminLogin: () => "/admin/login",
  adminDashboard: () => "/admin/dashboard",
  adminManageMembers: () => "/admin/ar/members",
  adminManagePlans: () => "/admin/ar/plans",
  adminManageSubscriptions: () => "/admin/ar/subscriptions",
  adminPaymentHistory: () => "/admin/ar/payments",
  adminCouponManagement: () => "/admin/ar/coupons",
  adminJobOpenings: () => "/admin/jobs/openings",
  adminAddNewJob: () => "/admin/jobs/add",
  adminApplications: () => "/admin/jobs/applications",
  adminAllUsers: () => "/admin/users/all",
  adminAddUser: () => "/admin/users/add",
  adminProfile: () => "/admin/users/profile",
  adminSettings: () => "/admin/settings",
  editor: () => "/admin/editor",
  // Content management routes
  adminNewsletterManagement: () => "/admin/content/newsletters",
  adminWebinarManagement: () => "/admin/content/webinars",
  adminPodcastManagement: () => "/admin/content/podcasts",
  adminNewsletterCreate: () => "/admin/content/newsletters/create",
  adminNewsletterEdit: () => "/admin/content/newsletters/:id/edit",
  adminWebinarCreate: () => "/admin/content/webinars/create",
  adminWebinarEdit: () => "/admin/content/webinars/:id/edit",
  adminPodcastCreate: () => "/admin/content/podcasts/create",
  adminPodcastEdit: () => "/admin/content/podcasts/:id/edit",
  adminResearchManagement: () => "/admin/content/research",
  adminResearchCreate: () => "/admin/content/research/create",
  adminResearchEdit: () => "/admin/content/research/:id/edit",
  // Public content routes
  newsletterView: () => "/newsletters/:id",
  webinarView: () => "/webinars/:id",
  podcastView: () => "/podcasts/:id",
  researchView: () => "/research/:id",
  ipoLanding: () => "/ipo-landing",
};

export const AuthRoutes = [
  AppRoutes.login(),
  AppRoutes.register(),
  AppRoutes.forgotPassword(),
  AppRoutes.resetPassword(),
];

export const AdminAuthRoutes = [AppRoutes.adminLogin()];
